### ISSUE TITLE
Interested in vulnerable cloud apps?

### ISSUE THREAD

**Issue by commjoen** [Funkmyster/awesome-cloud-security#2]
hi there, 
awesome list! I was wondering: would you be interested in adding projects like:
- OWASP serverless goat
- RhinoSecurity CloudGoat
- OWASP WrongSecrets

as they can explain a lot about security in the cloud in a practical sense?

With kind regards,
Jeroen

**Comment by Funkmyster** [comment]
@commjoen Thank you for the info on these projects!
